[pinga]
fetch.tarball = "https://css-ig.net/bin/pinga-win64.zip"
fetch.force = true
src.webpage = "https://css-ig.net/pinga"
src.regex = "v(\\d\\.\\d+\\.\\d+)"

[pingo]
fetch.tarball = "https://css-ig.net/bin/pingo-win64.zip"
fetch.force = true
src.webpage = "https://css-ig.net/pingo"
src.regex = "v(\\d\\.\\d+\\.\\d+)"

[rebelle-7]
fetch.url = "https://escapemotions1.b-cdn.net/products/rebelle/update/downloads/Rebelle_v$ver_Windows_64bit.exe"
src.webpage = "https://www.escapemotions.com/products/rebelle/download.php"
src.regex = "(7\\.\\d\\.\\d)"

[xwintab]
fetch.tarball = "https://github.com/Graham--M/XWinTab/releases/download/v$ver/XWinTab.v$ver.zip"
src.github = "Graham--M/XWinTab"
src.prefix = "v"
