# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchzip,
  fetchFromGitHub,
  dockerTools,
}:
{
  pinga = {
    pname = "pinga";
    version = "0.65.3";
    src = fetchzip {
      url = "https://css-ig.net/bin/pinga-win64.zip";
      sha256 = "sha256-Hos+/kuU3rWKdbV21HMt5cBBzwxSaj91iPc8ugeyBIw=";
    };
  };
  pingo = {
    pname = "pingo";
    version = "1.27.3";
    src = fetchzip {
      url = "https://css-ig.net/bin/pingo-win64.zip";
      sha256 = "sha256-VfEqAT1EaNyBXnFhg+djVYKCCgugpq8CyOz3ZvJCGjY=";
    };
  };
  rebelle-7 = {
    pname = "rebelle-7";
    version = "7.2.8";
    src = fetchurl {
      url = "https://escapemotions1.b-cdn.net/products/rebelle/update/downloads/Rebelle_v7.2.8_Windows_64bit.exe";
      sha256 = "sha256-hfuhaHZhITNWpurAhVOREE/EXZAzSLLHLK6P61BCT6c=";
    };
  };
  xwintab = {
    pname = "xwintab";
    version = "0.5.0";
    src = fetchzip {
      url = "https://github.com/Graham--M/XWinTab/releases/download/v0.5.0/XWinTab.v0.5.0.zip";
      sha256 = "sha256-nZ4aiY0ys5b/hP7+kXvUKKmkYSU9H3yTKh4x4+b1Jaw=";
    };
  };
}
