# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchzip,
  fetchFromGitHub,
  dockerTools,
}:
{
  autodesk-fusion = {
    pname = "autodesk-fusion";
    version = "0.0.0";
    src = fetchurl {
      url = "https://dl.appstreaming.autodesk.com/production/installers/Fusion%20Admin%20Install.exe";
      name = "FusionClientInstaller.exe";
      sha256 = "sha256-ad6toAMUDHvU9LRYIyf+scGgJI3QDzK3Aa059qQDkUk=";
    };
  };
  filmora-12 = {
    pname = "filmora-12";
    version = "12.5.7";
    src = fetchurl {
      url = "https://download.wondershare.com/cbs_down/filmora_64bit_12.5.7_full846.exe";
      sha256 = "sha256-iRF3yqd3zNSpElGVVGClu9e8OHknG6rvS79zAHb61Jg=";
    };
  };
  pinga = {
    pname = "pinga";
    version = "0.67";
    src = fetchzip {
      url = "https://css-ig.net/bin/pinga.zip";
      sha256 = "sha256-IzwzgSAtF5Qc7dtWekLFJb8I40BuJfhVhrslQrrAQHs=";
    };
  };
  pingo = {
    pname = "pingo";
    version = "1.29";
    src = fetchzip {
      url = "https://css-ig.net/bin/pingo.zip";
      sha256 = "sha256-wRgX7F8mIl+j/Rsq+8crdrEqiNEJorxUb6BEMG8VIJE=";
    };
  };
  rebelle-7 = {
    pname = "rebelle-7";
    version = "7.2.8";
    src = fetchurl {
      url = "https://escapemotions1.b-cdn.net/products/rebelle/update/downloads/Rebelle_v7.2.8_Windows_64bit.exe";
      sha256 = "sha256-hfuhaHZhITNWpurAhVOREE/EXZAzSLLHLK6P61BCT6c=";
    };
  };
  webview2 = {
    pname = "webview2";
    version = "0.0.0";
    src = fetchurl {
      url = "https://go.microsoft.com/fwlink/?linkid=2124701";
      name = "MicrosoftEdgeWebView2RuntimeInstallerX64.exe";
      sha256 = "sha256-H0Y4MJ89gsMaMCjDz311mY9Y5NFAc4D1y4qOkXLK8X0=";
    };
  };
  xwintab = {
    pname = "xwintab";
    version = "0.5.0";
    src = fetchzip {
      url = "https://github.com/Graham--M/XWinTab/releases/download/v0.5.0/XWinTab.v0.5.0.zip";
      sha256 = "sha256-nZ4aiY0ys5b/hP7+kXvUKKmkYSU9H3yTKh4x4+b1Jaw=";
    };
  };
}
